import type { Metadata } from "next";
import LayoutTop from "./layoutTop";
import LayoutBottom from "./layoutBottom";

import "./globals.css";
import "./app.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutTop />
        <div className="content">{children}</div>
        <LayoutBottom />
      </body>
    </html>
  );
}
